CREATE TABLE bills (id BIGINT NOT NULL PRIMARY KEY,
total INT, date DATE);

INSERT INTO bills VALUE (1, 20, '2021-05-08');

CREATE TABLE bills_drugs(id_bill BIGINT, id_drug BIGINT,
PRIMARY KEY (id_bill, id_drug), 
FOREIGN KEY (id_bill) REFERENCES bills(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (id_drug) REFERENCES drugs(id) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO bills_drugs VALUE (1, 1);
